print("Hello dear worker,")
X = input("How many hours did you work today:")
X = float(X)
print("Each working hour is 200 IRT")
print("Your salary is >>" , X*200 , "IRT << for today " )
print("Good job!")